### ISSUE TITLE
我修改出了2G

### ISSUE THREAD

**Issue by dysl357085918** [W2725730722/Lenovo-R7000P-2020-Hackintosh#1]

**Comment by dysl357085918** [comment]
我用UniversalAMDFormBrowser开了2g显存出来，图见

https://www.bilibili.com/read/cv24309337

前几天我刚倒腾过，没想到大佬们这么快就解决了我当时的大部分问题

**Comment by dysl357085918** [comment]
此外，有线网卡是可以驱动的，不用NullEthernet.kext，这一款的有线网卡是RTL8111

https://github.com/Mieze/RTL8111_driver_for_OS_X

**Comment by wushuo894** [comment]
> 此外，有线网卡是可以驱动的，不用NullEthernet.kext，这一款的有线网卡是RTL8111
> 
> https://github.com/Mieze/RTL8111_driver_for_OS_X

我忘了给11的efi加驱动

**Comment by dysl357085918** [comment]
总之，基本差不多了现在（除了睡眠、声音输入）。
