### ISSUE TITLE
1.7版EFI 安装big sur 出现EB错误，似乎是缺少东西 0.0

### ISSUE THREAD

**Issue by LOOPEER-A** [W2725730722/Lenovo-R7000P-2020-Hackintosh#5]
big sur 11.6.5正式版(20G517)
![EC 5F0}I4FL(`K7TON_06`B](https://github.com/W2725730722/Lenovo-R7000P-2020-Hackintosh/assets/85066207/0aa21a9e-cb32-449e-8032-4e7cf62ab889)

**Comment by wushuo894** [comment]
已重新上传

**Comment by LOOPEER-A** [comment]
感谢大佬！！
